// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SrNmcRpIsyQ0c8aAUTDEJRBKDnmtQfQ',
    appId: '1:131154421608:web:5eb6903d73614b965cd8dd',
    messagingSenderId: '131154421608',
    projectId: 'serenitylibrary-46699',
    authDomain: 'serenitylibrary-46699.firebaseapp.com',
    storageBucket: 'serenitylibrary-46699.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNIx7LOUZHcj3jCaZNpU64KvwVJ7fHMU',
    appId: '1:131154421608:android:d481b06fddb9e0c25cd8dd',
    messagingSenderId: '131154421608',
    projectId: 'serenitylibrary-46699',
    storageBucket: 'serenitylibrary-46699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEJ1kTlqKTIj6nCdxMk4-RAr4BawhEcCM',
    appId: '1:131154421608:ios:20eb7f3969eea3d75cd8dd',
    messagingSenderId: '131154421608',
    projectId: 'serenitylibrary-46699',
    storageBucket: 'serenitylibrary-46699.appspot.com',
    iosBundleId: 'com.example.serenity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEJ1kTlqKTIj6nCdxMk4-RAr4BawhEcCM',
    appId: '1:131154421608:ios:e6925c4efb707e125cd8dd',
    messagingSenderId: '131154421608',
    projectId: 'serenitylibrary-46699',
    storageBucket: 'serenitylibrary-46699.appspot.com',
    iosBundleId: 'com.example.serenity.RunnerTests',
  );
}
